### ISSUE TITLE
Abstract repository should implement an interface

### ISSUE THREAD

**Issue by pabl0rg** [micheleangioni/phalcon-repositories#1]
As far as I can tell, the main point of repositories is unit testability.  (Otherwise, we'd just use the methods that phalcon provides for Models).

In order to mock out the repos, we could use an interface instead of just and abstract class.

**Comment by micheleangioni** [comment]
Hi @pabl0rg ,
testing repositories is always a controversial topic. People use this kind of packages to enhance the base framework querying / ORM methods, just using base Phalcon methods in all repositories would be a pain (and it requires more testing efforts).

Moreover often repositories are kept quite simple, by concentrating the businell login in Domain or Application Services. In this case it's indeed importart to mock the repos For this reason, I added an Interface with the current developed repo methods as you suggested.

Bye.
